cc_binary(
    name = 'db',
    srcs = [
        'main.cc',
    ],
    deps = [
        '//thirdparty/csv_parser',
        '@com_google_absl//absl/strings',
    ],
    copts = [
        '-Wall',
        '-Wold-style-cast',
        #'-Werror',
    ],
)
